# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "fps_voeventdb_testvm" do |fps_voeventdb_testvm| end

  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5050

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../provisioning/deploy.yml"
    ansible.verbose = "vv"
    ansible.groups = {
      "test" => ["fps_voeventdb_testvm"],
      "test:vars" => {"ansible_python_interpreter" => "/usr/bin/python3"}
      }
  end

end

